### ISSUE TITLE
Possible typo in Pt. 2 Map files example

### ISSUE THREAD

**Issue by d2r** [iffyio/iffyio.github.io#2]
In [2019-07-10-linux-namespaces-part-2.md](https://github.com/iffyio/iffyio.github.io/blob/8577c862ed820deaa1ab3ec809c404c62451036b/_posts/2019-07-10-linux-namespaces-part-2.md) we have:
```
P$ echo $$
1442
# In a new user namespace...
C$ echo $$
1409
# C has no mappings to it's parent since it is new
C$ cat /proc/1409/uid_map
# Empty
# While root namespace P has dummy mappings for all
# UIDs to the same UID in its non-existent parent
P$ cat /proc/1442/uid_map
         0          0 4294967295
# UIDs 0 through 4294967294 in P is mapped
# to 4294967295 - the special no user ID - in C.
C$ cat /proc/1409/uid_map
         0 4294967295 4294967295
```

I was expecting the final command here to use the parent PID:
```Diff
15c15
< C$ cat /proc/1409/uid_map
---
> C$ cat /proc/1422/uid_map
```
Otherwise, wouldn't this map file read empty, as it is still the child process doing the read?

**Comment by iffyio** [comment]
Hi! the command should be as is - here's a section from the post that I think might explain why:

> Each row has the format $fromID $toID $length

> Translating $toID is dependent on the reading process X. If X belongs to a different user namespace U, then $toID is the start UID of the range in U to which $fromID maps. Otherwise, $toID is the start UID of the range in P, the parent user namespace of C.

In this case, the reading process is itself the child process `C` so it's reading its own map file (and it belongs to the same user namespace as itself) - in which case the returned row is really a mapping to its parent process `P`

**Comment by d2r** [comment]
Thank you for your reply!

```Bash
# C has no mappings to it's parent since it is new
C$ cat /proc/1409/uid_map
# Empty
```
This is Case 1) A `cat` process in the child namespace `C` reads the map for the PID of `C$` -> _EMPTY_


```Bash
# While root namespace P has dummy mappings for all
# UIDs to the same UID in its non-existent parent
P$ cat /proc/1442/uid_map
         0          0 4294967295
```
This is Case 2) A `cat` process in the parent namespace `P` reads the map for the PID of `P$` ->  `0 0 4294967295`


```Bash
# UIDs 0 through 4294967294 in P is mapped
# to 4294967295 - the special no user ID - in C.
C$ cat /proc/1409/uid_map
         0 4294967295 4294967295
```
This is Case 3) A `cat` process in the child namespace `C` reads the map for the PID of `C$` -> `0 4294967295 4294967295`

But are not Cases 1) and 3) equivalent? If they are not, the difference is not apparent to me.


I tried to replicate this, and I got the following:
```Bash
[vagrant@archlinux ~]$ echo $$
512
[vagrant@archlinux ~]$ unshare -U bash
[nobody@iffy ~]$ echo $$
3285
[nobody@iffy ~]$ cat /proc/3285/uid_map
[nobody@iffy ~]$ cat /proc/512/uid_map
         0 4294967295 4294967295
[nobody@iffy ~]$ exit
[vagrant@archlinux ~]$ cat /proc/512/uid_map
         0          0 4294967295
```

I may still be missing something here...

**Comment by iffyio** [comment]
Ah, I think I see what you mean now. In the example `C` is in a new namespace so there are no mappings for it to begin with (case 1 and 3 are equivalent and should both be empty) and a way to see a mapping into the parent namespace would be to read the parent map file. You're right! this is a typo `C$ cat /proc/1409/uid_map` should be `C$ cat /proc/1422/uid_map`. Thanks for catching this! you're more than welcome to fix this in a PR if you would like to ;)

**Comment by d2r** [comment]
Sure no problem, will take a look.
